# Generated by Django 4.2.1 on 2023-06-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_creared_message_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': []},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='creared',
            new_name='created',
        ),
    ]
